# Generated by Django 3.1.7 on 2021-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210401_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('delivary_address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=150)),
                ('delivery_within_what_time', models.CharField(max_length=150)),
                ('alternative_contact_name', models.CharField(max_length=150)),
                ('alternative_contact_number', models.CharField(max_length=150)),
                ('payment_method', models.CharField(max_length=150)),
            ],
        ),
    ]
