# Generated by Django 3.1.7 on 2021-04-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0002_auto_20210401_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('invoice_id', models.TextField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivary_charge', models.IntegerField()),
                ('transport_cost', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('due', models.IntegerField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
