# Generated by Django 3.1.7 on 2021-04-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='customer_id',
            new_name='user_id',
        ),
    ]
