# Generated by Django 3.1.7 on 2021-04-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_admin',
            fields=[
                ('inv_admin_id', models.TextField(primary_key=True, serialize=False)),
                ('inv_admin_name', models.CharField(max_length=50)),
                ('inv_admin_email', models.CharField(max_length=50)),
            ],
        ),
    ]
